package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmUniqData generated by hbm2java
 */
@Entity
@Table(name = "adm_uniq_data")
public class AdmUniqData implements java.io.Serializable {

	private String uniqSeq;
	private Date recordDate;
	private String uniqName;
	private int uniqCount;
	private Date createDate;
	private Date updateDate;

	public AdmUniqData() {
	}

	public AdmUniqData(String uniqSeq, Date recordDate, String uniqName, int uniqCount, Date createDate,
			Date updateDate) {
		this.uniqSeq = uniqSeq;
		this.recordDate = recordDate;
		this.uniqName = uniqName;
		this.uniqCount = uniqCount;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "uniq_seq", unique = true, nullable = false, length = 30)
	public String getUniqSeq() {
		return this.uniqSeq;
	}

	public void setUniqSeq(String uniqSeq) {
		this.uniqSeq = uniqSeq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 10)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "uniq_name", nullable = false, length = 20)
	public String getUniqName() {
		return this.uniqName;
	}

	public void setUniqName(String uniqName) {
		this.uniqName = uniqName;
	}

	@Column(name = "uniq_count", nullable = false)
	public int getUniqCount() {
		return this.uniqCount;
	}

	public void setUniqCount(int uniqCount) {
		this.uniqCount = uniqCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
