package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfpAdSpecificWebsite generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_specific_website")
public class PfpAdSpecificWebsite implements java.io.Serializable {

	private String specificWebsiteSeq;
	private PfbxWebsiteCategory pfbxWebsiteCategory;
	private PfpAdAction pfpAdAction;

	public PfpAdSpecificWebsite() {
	}

	public PfpAdSpecificWebsite(String specificWebsiteSeq, PfbxWebsiteCategory pfbxWebsiteCategory,
			PfpAdAction pfpAdAction) {
		this.specificWebsiteSeq = specificWebsiteSeq;
		this.pfbxWebsiteCategory = pfbxWebsiteCategory;
		this.pfpAdAction = pfpAdAction;
	}

	@Id

	@Column(name = "specific_website_seq", unique = true, nullable = false, length = 20)
	public String getSpecificWebsiteSeq() {
		return this.specificWebsiteSeq;
	}

	public void setSpecificWebsiteSeq(String specificWebsiteSeq) {
		this.specificWebsiteSeq = specificWebsiteSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "website_ref", nullable = false)
	public PfbxWebsiteCategory getPfbxWebsiteCategory() {
		return this.pfbxWebsiteCategory;
	}

	public void setPfbxWebsiteCategory(PfbxWebsiteCategory pfbxWebsiteCategory) {
		this.pfbxWebsiteCategory = pfbxWebsiteCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_action_seq", nullable = false)
	public PfpAdAction getPfpAdAction() {
		return this.pfpAdAction;
	}

	public void setPfpAdAction(PfpAdAction pfpAdAction) {
		this.pfpAdAction = pfpAdAction;
	}

}
