package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdSysprice generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_sysprice")
public class PfpAdSysprice implements java.io.Serializable {

	private Integer id;
	private String adPoolSeq;
	private float sysprice;
	private int amount;
	private Date updateDate;
	private Date createDate;

	public PfpAdSysprice() {
	}

	public PfpAdSysprice(String adPoolSeq, float sysprice, int amount, Date updateDate, Date createDate) {
		this.adPoolSeq = adPoolSeq;
		this.sysprice = sysprice;
		this.amount = amount;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ad_pool_seq", nullable = false, length = 20)
	public String getAdPoolSeq() {
		return this.adPoolSeq;
	}

	public void setAdPoolSeq(String adPoolSeq) {
		this.adPoolSeq = adPoolSeq;
	}

	@Column(name = "sysprice", nullable = false, precision = 10)
	public float getSysprice() {
		return this.sysprice;
	}

	public void setSysprice(float sysprice) {
		this.sysprice = sysprice;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
