package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdVideoSource generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_video_source")
public class PfpAdVideoSource implements java.io.Serializable {

	private String adVideoSeq;
	private String adVideoWebmPath;
	private String adVideoMp4Path;
	private int adVideoStatus;
	private String videoVertical;
	private String adVideoUrl;
	private Date updateDate;
	private Date createDate;

	public PfpAdVideoSource() {
	}

	public PfpAdVideoSource(String adVideoSeq, int adVideoStatus, String adVideoUrl, Date updateDate, Date createDate) {
		this.adVideoSeq = adVideoSeq;
		this.adVideoStatus = adVideoStatus;
		this.adVideoUrl = adVideoUrl;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpAdVideoSource(String adVideoSeq, String adVideoWebmPath, String adVideoMp4Path, int adVideoStatus,
			String videoVertical, String adVideoUrl, Date updateDate, Date createDate) {
		this.adVideoSeq = adVideoSeq;
		this.adVideoWebmPath = adVideoWebmPath;
		this.adVideoMp4Path = adVideoMp4Path;
		this.adVideoStatus = adVideoStatus;
		this.videoVertical = videoVertical;
		this.adVideoUrl = adVideoUrl;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "ad_video_seq", unique = true, nullable = false, length = 20)
	public String getAdVideoSeq() {
		return this.adVideoSeq;
	}

	public void setAdVideoSeq(String adVideoSeq) {
		this.adVideoSeq = adVideoSeq;
	}

	@Column(name = "ad_video_webm_path", length = 2048)
	public String getAdVideoWebmPath() {
		return this.adVideoWebmPath;
	}

	public void setAdVideoWebmPath(String adVideoWebmPath) {
		this.adVideoWebmPath = adVideoWebmPath;
	}

	@Column(name = "ad_video_mp4_path", length = 2048)
	public String getAdVideoMp4Path() {
		return this.adVideoMp4Path;
	}

	public void setAdVideoMp4Path(String adVideoMp4Path) {
		this.adVideoMp4Path = adVideoMp4Path;
	}

	@Column(name = "ad_video_status", nullable = false)
	public int getAdVideoStatus() {
		return this.adVideoStatus;
	}

	public void setAdVideoStatus(int adVideoStatus) {
		this.adVideoStatus = adVideoStatus;
	}

	@Column(name = "video_vertical", length = 1)
	public String getVideoVertical() {
		return this.videoVertical;
	}

	public void setVideoVertical(String videoVertical) {
		this.videoVertical = videoVertical;
	}

	@Column(name = "ad_video_url", nullable = false, length = 2048)
	public String getAdVideoUrl() {
		return this.adVideoUrl;
	}

	public void setAdVideoUrl(String adVideoUrl) {
		this.adVideoUrl = adVideoUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
