package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCodeConvertTrans generated by hbm2java
 */
@Entity
@Table(name = "pfp_code_convert_trans")
public class PfpCodeConvertTrans implements java.io.Serializable {

	private Integer id;
	private String uuid;
	private String convertDate;
	private String convertSeq;
	private String convertTriggerType;
	private String convertNumType;
	private String convertBelong;
	private String convertBelongDate;
	private int convertCount;
	private int convertPrice;
	private String adSeq;
	private String adGroupSeq;
	private String adActionSeq;
	private String adType;
	private String adPvclkDate;
	private String adPvclkTime;
	private String customerInfoId;
	private String pfbxCustomerInfoId;
	private String pfbxPositionId;
	private String pfdCustomerInfoId;
	private String payType;
	private String sex;
	private String ageCode;
	private String timeCode;
	private String templateAdSeq;
	private String adPvclkWebsiteClassify;
	private String adPvclkAudienceClassify;
	private String adUrl;
	private String styleNo;
	private String adPvclkDevice;
	private String adPvclkOs;
	private String adPvclkBrand;
	private String adPvclkArea;
	private Date updateDate;
	private Date createDate;

	public PfpCodeConvertTrans() {
	}

	public PfpCodeConvertTrans(String uuid, String convertDate, String convertSeq, String convertTriggerType,
			String convertNumType, String convertBelong, String convertBelongDate, int convertCount, int convertPrice,
			String adSeq, String adGroupSeq, String adActionSeq, String adType, String adPvclkDate, String adPvclkTime,
			String customerInfoId, String pfbxCustomerInfoId, String pfbxPositionId, String pfdCustomerInfoId,
			String payType, Date updateDate, Date createDate) {
		this.uuid = uuid;
		this.convertDate = convertDate;
		this.convertSeq = convertSeq;
		this.convertTriggerType = convertTriggerType;
		this.convertNumType = convertNumType;
		this.convertBelong = convertBelong;
		this.convertBelongDate = convertBelongDate;
		this.convertCount = convertCount;
		this.convertPrice = convertPrice;
		this.adSeq = adSeq;
		this.adGroupSeq = adGroupSeq;
		this.adActionSeq = adActionSeq;
		this.adType = adType;
		this.adPvclkDate = adPvclkDate;
		this.adPvclkTime = adPvclkTime;
		this.customerInfoId = customerInfoId;
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
		this.pfbxPositionId = pfbxPositionId;
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.payType = payType;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpCodeConvertTrans(String uuid, String convertDate, String convertSeq, String convertTriggerType,
			String convertNumType, String convertBelong, String convertBelongDate, int convertCount, int convertPrice,
			String adSeq, String adGroupSeq, String adActionSeq, String adType, String adPvclkDate, String adPvclkTime,
			String customerInfoId, String pfbxCustomerInfoId, String pfbxPositionId, String pfdCustomerInfoId,
			String payType, String sex, String ageCode, String timeCode, String templateAdSeq,
			String adPvclkWebsiteClassify, String adPvclkAudienceClassify, String adUrl, String styleNo,
			String adPvclkDevice, String adPvclkOs, String adPvclkBrand, String adPvclkArea, Date updateDate,
			Date createDate) {
		this.uuid = uuid;
		this.convertDate = convertDate;
		this.convertSeq = convertSeq;
		this.convertTriggerType = convertTriggerType;
		this.convertNumType = convertNumType;
		this.convertBelong = convertBelong;
		this.convertBelongDate = convertBelongDate;
		this.convertCount = convertCount;
		this.convertPrice = convertPrice;
		this.adSeq = adSeq;
		this.adGroupSeq = adGroupSeq;
		this.adActionSeq = adActionSeq;
		this.adType = adType;
		this.adPvclkDate = adPvclkDate;
		this.adPvclkTime = adPvclkTime;
		this.customerInfoId = customerInfoId;
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
		this.pfbxPositionId = pfbxPositionId;
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.payType = payType;
		this.sex = sex;
		this.ageCode = ageCode;
		this.timeCode = timeCode;
		this.templateAdSeq = templateAdSeq;
		this.adPvclkWebsiteClassify = adPvclkWebsiteClassify;
		this.adPvclkAudienceClassify = adPvclkAudienceClassify;
		this.adUrl = adUrl;
		this.styleNo = styleNo;
		this.adPvclkDevice = adPvclkDevice;
		this.adPvclkOs = adPvclkOs;
		this.adPvclkBrand = adPvclkBrand;
		this.adPvclkArea = adPvclkArea;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uuid", nullable = false, length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "convert_date", nullable = false, length = 10)
	public String getConvertDate() {
		return this.convertDate;
	}

	public void setConvertDate(String convertDate) {
		this.convertDate = convertDate;
	}

	@Column(name = "convert_seq", nullable = false, length = 20)
	public String getConvertSeq() {
		return this.convertSeq;
	}

	public void setConvertSeq(String convertSeq) {
		this.convertSeq = convertSeq;
	}

	@Column(name = "convert_trigger_type", nullable = false, length = 2)
	public String getConvertTriggerType() {
		return this.convertTriggerType;
	}

	public void setConvertTriggerType(String convertTriggerType) {
		this.convertTriggerType = convertTriggerType;
	}

	@Column(name = "convert_num_type", nullable = false, length = 1)
	public String getConvertNumType() {
		return this.convertNumType;
	}

	public void setConvertNumType(String convertNumType) {
		this.convertNumType = convertNumType;
	}

	@Column(name = "convert_belong", nullable = false, length = 1)
	public String getConvertBelong() {
		return this.convertBelong;
	}

	public void setConvertBelong(String convertBelong) {
		this.convertBelong = convertBelong;
	}

	@Column(name = "convert_belong_date", nullable = false, length = 10)
	public String getConvertBelongDate() {
		return this.convertBelongDate;
	}

	public void setConvertBelongDate(String convertBelongDate) {
		this.convertBelongDate = convertBelongDate;
	}

	@Column(name = "convert_count", nullable = false)
	public int getConvertCount() {
		return this.convertCount;
	}

	public void setConvertCount(int convertCount) {
		this.convertCount = convertCount;
	}

	@Column(name = "convert_price", nullable = false)
	public int getConvertPrice() {
		return this.convertPrice;
	}

	public void setConvertPrice(int convertPrice) {
		this.convertPrice = convertPrice;
	}

	@Column(name = "ad_seq", nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "ad_group_seq", nullable = false, length = 20)
	public String getAdGroupSeq() {
		return this.adGroupSeq;
	}

	public void setAdGroupSeq(String adGroupSeq) {
		this.adGroupSeq = adGroupSeq;
	}

	@Column(name = "ad_action_seq", nullable = false, length = 20)
	public String getAdActionSeq() {
		return this.adActionSeq;
	}

	public void setAdActionSeq(String adActionSeq) {
		this.adActionSeq = adActionSeq;
	}

	@Column(name = "ad_type", nullable = false, length = 1)
	public String getAdType() {
		return this.adType;
	}

	public void setAdType(String adType) {
		this.adType = adType;
	}

	@Column(name = "ad_pvclk_date", nullable = false, length = 10)
	public String getAdPvclkDate() {
		return this.adPvclkDate;
	}

	public void setAdPvclkDate(String adPvclkDate) {
		this.adPvclkDate = adPvclkDate;
	}

	@Column(name = "ad_pvclk_time", nullable = false, length = 3)
	public String getAdPvclkTime() {
		return this.adPvclkTime;
	}

	public void setAdPvclkTime(String adPvclkTime) {
		this.adPvclkTime = adPvclkTime;
	}

	@Column(name = "customer_info_id", nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "pfbx_customer_info_id", nullable = false, length = 20)
	public String getPfbxCustomerInfoId() {
		return this.pfbxCustomerInfoId;
	}

	public void setPfbxCustomerInfoId(String pfbxCustomerInfoId) {
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
	}

	@Column(name = "pfbx_position_id", nullable = false, length = 20)
	public String getPfbxPositionId() {
		return this.pfbxPositionId;
	}

	public void setPfbxPositionId(String pfbxPositionId) {
		this.pfbxPositionId = pfbxPositionId;
	}

	@Column(name = "pfd_customer_info_id", nullable = false, length = 20)
	public String getPfdCustomerInfoId() {
		return this.pfdCustomerInfoId;
	}

	public void setPfdCustomerInfoId(String pfdCustomerInfoId) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "sex", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "age_code", length = 20)
	public String getAgeCode() {
		return this.ageCode;
	}

	public void setAgeCode(String ageCode) {
		this.ageCode = ageCode;
	}

	@Column(name = "time_code", length = 20)
	public String getTimeCode() {
		return this.timeCode;
	}

	public void setTimeCode(String timeCode) {
		this.timeCode = timeCode;
	}

	@Column(name = "template_ad_seq", length = 20)
	public String getTemplateAdSeq() {
		return this.templateAdSeq;
	}

	public void setTemplateAdSeq(String templateAdSeq) {
		this.templateAdSeq = templateAdSeq;
	}

	@Column(name = "ad_pvclk_website_classify", length = 20)
	public String getAdPvclkWebsiteClassify() {
		return this.adPvclkWebsiteClassify;
	}

	public void setAdPvclkWebsiteClassify(String adPvclkWebsiteClassify) {
		this.adPvclkWebsiteClassify = adPvclkWebsiteClassify;
	}

	@Column(name = "ad_pvclk_audience_classify", length = 20)
	public String getAdPvclkAudienceClassify() {
		return this.adPvclkAudienceClassify;
	}

	public void setAdPvclkAudienceClassify(String adPvclkAudienceClassify) {
		this.adPvclkAudienceClassify = adPvclkAudienceClassify;
	}

	@Column(name = "ad_url", length = 2048)
	public String getAdUrl() {
		return this.adUrl;
	}

	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl;
	}

	@Column(name = "style_no", length = 20)
	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

	@Column(name = "ad_pvclk_device", length = 20)
	public String getAdPvclkDevice() {
		return this.adPvclkDevice;
	}

	public void setAdPvclkDevice(String adPvclkDevice) {
		this.adPvclkDevice = adPvclkDevice;
	}

	@Column(name = "ad_pvclk_os", length = 20)
	public String getAdPvclkOs() {
		return this.adPvclkOs;
	}

	public void setAdPvclkOs(String adPvclkOs) {
		this.adPvclkOs = adPvclkOs;
	}

	@Column(name = "ad_pvclk_brand", length = 20)
	public String getAdPvclkBrand() {
		return this.adPvclkBrand;
	}

	public void setAdPvclkBrand(String adPvclkBrand) {
		this.adPvclkBrand = adPvclkBrand;
	}

	@Column(name = "ad_pvclk_area", length = 20)
	public String getAdPvclkArea() {
		return this.adPvclkArea;
	}

	public void setAdPvclkArea(String adPvclkArea) {
		this.adPvclkArea = adPvclkArea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
