package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogLogo generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_logo")
public class PfpCatalogLogo implements java.io.Serializable {

	private String catalogLogoSeq;
	private String pfpCustomerInfoId;
	private String catalogLogoType;
	private String catalogLogoUrl;
	private String status;
	private Date logoSendVerifyTime;
	private Date logoUserVerifyTime;
	private String logoVerifyUser;
	private String logoVerifyRejectReason;
	private Date updateDate;
	private Date createDate;
	private Set<PfpCatalogLogoDetail> pfpCatalogLogoDetails = new HashSet<PfpCatalogLogoDetail>(0);

	public PfpCatalogLogo() {
	}

	public PfpCatalogLogo(String catalogLogoSeq, String pfpCustomerInfoId, String catalogLogoType,
			String catalogLogoUrl, String status, Date updateDate, Date createDate) {
		this.catalogLogoSeq = catalogLogoSeq;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.catalogLogoType = catalogLogoType;
		this.catalogLogoUrl = catalogLogoUrl;
		this.status = status;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpCatalogLogo(String catalogLogoSeq, String pfpCustomerInfoId, String catalogLogoType,
			String catalogLogoUrl, String status, Date logoSendVerifyTime, Date logoUserVerifyTime,
			String logoVerifyUser, String logoVerifyRejectReason, Date updateDate, Date createDate,
			Set<PfpCatalogLogoDetail> pfpCatalogLogoDetails) {
		this.catalogLogoSeq = catalogLogoSeq;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.catalogLogoType = catalogLogoType;
		this.catalogLogoUrl = catalogLogoUrl;
		this.status = status;
		this.logoSendVerifyTime = logoSendVerifyTime;
		this.logoUserVerifyTime = logoUserVerifyTime;
		this.logoVerifyUser = logoVerifyUser;
		this.logoVerifyRejectReason = logoVerifyRejectReason;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.pfpCatalogLogoDetails = pfpCatalogLogoDetails;
	}

	@Id

	@Column(name = "catalog_logo_seq", unique = true, nullable = false, length = 20)
	public String getCatalogLogoSeq() {
		return this.catalogLogoSeq;
	}

	public void setCatalogLogoSeq(String catalogLogoSeq) {
		this.catalogLogoSeq = catalogLogoSeq;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "catalog_logo_type", nullable = false, length = 1)
	public String getCatalogLogoType() {
		return this.catalogLogoType;
	}

	public void setCatalogLogoType(String catalogLogoType) {
		this.catalogLogoType = catalogLogoType;
	}

	@Column(name = "catalog_logo_url", nullable = false, length = 2048)
	public String getCatalogLogoUrl() {
		return this.catalogLogoUrl;
	}

	public void setCatalogLogoUrl(String catalogLogoUrl) {
		this.catalogLogoUrl = catalogLogoUrl;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logo_send_verify_time", length = 19)
	public Date getLogoSendVerifyTime() {
		return this.logoSendVerifyTime;
	}

	public void setLogoSendVerifyTime(Date logoSendVerifyTime) {
		this.logoSendVerifyTime = logoSendVerifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logo_user_verify_time", length = 19)
	public Date getLogoUserVerifyTime() {
		return this.logoUserVerifyTime;
	}

	public void setLogoUserVerifyTime(Date logoUserVerifyTime) {
		this.logoUserVerifyTime = logoUserVerifyTime;
	}

	@Column(name = "logo_verify_user", length = 50)
	public String getLogoVerifyUser() {
		return this.logoVerifyUser;
	}

	public void setLogoVerifyUser(String logoVerifyUser) {
		this.logoVerifyUser = logoVerifyUser;
	}

	@Column(name = "logo_verify_reject_reason", length = 200)
	public String getLogoVerifyRejectReason() {
		return this.logoVerifyRejectReason;
	}

	public void setLogoVerifyRejectReason(String logoVerifyRejectReason) {
		this.logoVerifyRejectReason = logoVerifyRejectReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfpCatalogLogo")
	public Set<PfpCatalogLogoDetail> getPfpCatalogLogoDetails() {
		return this.pfpCatalogLogoDetails;
	}

	public void setPfpCatalogLogoDetails(Set<PfpCatalogLogoDetail> pfpCatalogLogoDetails) {
		this.pfpCatalogLogoDetails = pfpCatalogLogoDetails;
	}

}
