package com.pchome.akbpfp.db.pojo;
// Generated 2019/3/6 �U�� 01:55:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCodeTracking generated by hbm2java
 */
@Entity
@Table(name = "pfp_code_tracking")
public class PfpCodeTracking implements java.io.Serializable {

	private String trackingSeq;
	private PfpCode pfpCode;
	private String trackingName;
	private String pfpCustomerInfoId;
	private String trackingStatus;
	private String codeType;
	private int trackingRangeDate;
	private Date updateDate;
	private Date createDate;

	public PfpCodeTracking() {
	}

	public PfpCodeTracking(String trackingSeq, PfpCode pfpCode, String trackingName, String pfpCustomerInfoId,
			String trackingStatus, String codeType, int trackingRangeDate, Date updateDate, Date createDate) {
		this.trackingSeq = trackingSeq;
		this.pfpCode = pfpCode;
		this.trackingName = trackingName;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.trackingStatus = trackingStatus;
		this.codeType = codeType;
		this.trackingRangeDate = trackingRangeDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "tracking_seq", unique = true, nullable = false, length = 20)
	public String getTrackingSeq() {
		return this.trackingSeq;
	}

	public void setTrackingSeq(String trackingSeq) {
		this.trackingSeq = trackingSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pa_id", nullable = false)
	public PfpCode getPfpCode() {
		return this.pfpCode;
	}

	public void setPfpCode(PfpCode pfpCode) {
		this.pfpCode = pfpCode;
	}

	@Column(name = "tracking_name", nullable = false, length = 20)
	public String getTrackingName() {
		return this.trackingName;
	}

	public void setTrackingName(String trackingName) {
		this.trackingName = trackingName;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "tracking_status", nullable = false, length = 1)
	public String getTrackingStatus() {
		return this.trackingStatus;
	}

	public void setTrackingStatus(String trackingStatus) {
		this.trackingStatus = trackingStatus;
	}

	@Column(name = "code_type", nullable = false, length = 1)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "tracking_range_date", nullable = false)
	public int getTrackingRangeDate() {
		return this.trackingRangeDate;
	}

	public void setTrackingRangeDate(int trackingRangeDate) {
		this.trackingRangeDate = trackingRangeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
