package com.pchome.akbpfp.db.pojo;
// Generated 2018/12/7 �W�� 10:31:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdmTemplateProduct generated by hbm2java
 */
@Entity
@Table(name = "adm_template_product")
public class AdmTemplateProduct implements java.io.Serializable {

	private String templateProductSeq;
	private String templateProductName;
	private String templateProductWidth;
	private String templateProductHeight;
	private int admTemplateAdType;
	private int adType;
	private String templateProductXtype;
	private int pageTotalNum;
	private int startNum;
	private String iframeWidth;
	private String iframeHeight;
	private String templateProductFile;
	private int templateAdCount;
	private String templateProductShow;

	public AdmTemplateProduct() {
	}

	public AdmTemplateProduct(String templateProductSeq, String templateProductName, String templateProductWidth,
			String templateProductHeight, int admTemplateAdType, int adType, String templateProductXtype,
			int pageTotalNum, int startNum, String iframeWidth, String iframeHeight, String templateProductFile,
			int templateAdCount, String templateProductShow) {
		this.templateProductSeq = templateProductSeq;
		this.templateProductName = templateProductName;
		this.templateProductWidth = templateProductWidth;
		this.templateProductHeight = templateProductHeight;
		this.admTemplateAdType = admTemplateAdType;
		this.adType = adType;
		this.templateProductXtype = templateProductXtype;
		this.pageTotalNum = pageTotalNum;
		this.startNum = startNum;
		this.iframeWidth = iframeWidth;
		this.iframeHeight = iframeHeight;
		this.templateProductFile = templateProductFile;
		this.templateAdCount = templateAdCount;
		this.templateProductShow = templateProductShow;
	}

	@Id

	@Column(name = "template_product_seq", unique = true, nullable = false, length = 50)
	public String getTemplateProductSeq() {
		return this.templateProductSeq;
	}

	public void setTemplateProductSeq(String templateProductSeq) {
		this.templateProductSeq = templateProductSeq;
	}

	@Column(name = "template_product_name", nullable = false, length = 20)
	public String getTemplateProductName() {
		return this.templateProductName;
	}

	public void setTemplateProductName(String templateProductName) {
		this.templateProductName = templateProductName;
	}

	@Column(name = "template_product_width", nullable = false, length = 4)
	public String getTemplateProductWidth() {
		return this.templateProductWidth;
	}

	public void setTemplateProductWidth(String templateProductWidth) {
		this.templateProductWidth = templateProductWidth;
	}

	@Column(name = "template_product_height", nullable = false, length = 4)
	public String getTemplateProductHeight() {
		return this.templateProductHeight;
	}

	public void setTemplateProductHeight(String templateProductHeight) {
		this.templateProductHeight = templateProductHeight;
	}

	@Column(name = "adm_template_ad_type", nullable = false)
	public int getAdmTemplateAdType() {
		return this.admTemplateAdType;
	}

	public void setAdmTemplateAdType(int admTemplateAdType) {
		this.admTemplateAdType = admTemplateAdType;
	}

	@Column(name = "ad_type", nullable = false)
	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	@Column(name = "template_product_xtype", nullable = false, length = 10)
	public String getTemplateProductXtype() {
		return this.templateProductXtype;
	}

	public void setTemplateProductXtype(String templateProductXtype) {
		this.templateProductXtype = templateProductXtype;
	}

	@Column(name = "page_total_num", nullable = false)
	public int getPageTotalNum() {
		return this.pageTotalNum;
	}

	public void setPageTotalNum(int pageTotalNum) {
		this.pageTotalNum = pageTotalNum;
	}

	@Column(name = "start_num", nullable = false)
	public int getStartNum() {
		return this.startNum;
	}

	public void setStartNum(int startNum) {
		this.startNum = startNum;
	}

	@Column(name = "iframe_width", nullable = false, length = 4)
	public String getIframeWidth() {
		return this.iframeWidth;
	}

	public void setIframeWidth(String iframeWidth) {
		this.iframeWidth = iframeWidth;
	}

	@Column(name = "iframe_height", nullable = false, length = 4)
	public String getIframeHeight() {
		return this.iframeHeight;
	}

	public void setIframeHeight(String iframeHeight) {
		this.iframeHeight = iframeHeight;
	}

	@Column(name = "template_product_file", nullable = false, length = 500)
	public String getTemplateProductFile() {
		return this.templateProductFile;
	}

	public void setTemplateProductFile(String templateProductFile) {
		this.templateProductFile = templateProductFile;
	}

	@Column(name = "template_ad_count", nullable = false)
	public int getTemplateAdCount() {
		return this.templateAdCount;
	}

	public void setTemplateAdCount(int templateAdCount) {
		this.templateAdCount = templateAdCount;
	}

	@Column(name = "template_product_show", nullable = false, length = 3)
	public String getTemplateProductShow() {
		return this.templateProductShow;
	}

	public void setTemplateProductShow(String templateProductShow) {
		this.templateProductShow = templateProductShow;
	}

}
