package com.pchome.akbpfp.db.pojo;
// Generated 2017/8/21 �U�� 01:20:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmUniqData generated by hbm2java
 */
@Entity
@Table(name = "adm_uniq_data", catalog = "akb_video")
public class AdmUniqData implements java.io.Serializable {

	private Integer uniqSeq;
	private Date recordDate;
	private String uniqName;
	private int uniqCount;
	private Date createDate;
	private Date updateDate;

	public AdmUniqData() {
	}

	public AdmUniqData(Date recordDate, String uniqName, int uniqCount, Date createDate, Date updateDate) {
		this.recordDate = recordDate;
		this.uniqName = uniqName;
		this.uniqCount = uniqCount;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uniq_seq", unique = true, nullable = false)
	public Integer getUniqSeq() {
		return this.uniqSeq;
	}

	public void setUniqSeq(Integer uniqSeq) {
		this.uniqSeq = uniqSeq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 0)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "uniq_name", nullable = false, length = 20)
	public String getUniqName() {
		return this.uniqName;
	}

	public void setUniqName(String uniqName) {
		this.uniqName = uniqName;
	}

	@Column(name = "uniq_count", nullable = false)
	public int getUniqCount() {
		return this.uniqCount;
	}

	public void setUniqCount(int uniqCount) {
		this.uniqCount = uniqCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
