package com.pchome.akbpfp.db.pojo;

// Generated Jul 14, 2015 12:06:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdFixedBonusDetail generated by hbm2java
 */
@Entity
@Table(name = "pfd_fixed_bonus_detail", catalog = "akb")
public class PfdFixedBonusDetail implements java.io.Serializable {

    private Integer bonusDetailId;
    private PfpCustomerInfo pfpCustomerInfo;
    private PfdCustomerInfo pfdCustomerInfo;
    private PfdBonusItem pfdBonusItem;
    private int year;
    private int month;
    private int quarter;
    private String payType;
    private String monthBonus;
    private String fixedName;
    private String fixedDesc;
    private float adClickCost;
    private float bonusPercent;
    private float bonusMoney;
    private Date createDate;
    private Date updateDate;

    public PfdFixedBonusDetail() {
    }

    public PfdFixedBonusDetail(PfpCustomerInfo pfpCustomerInfo,
	    PfdCustomerInfo pfdCustomerInfo, PfdBonusItem pfdBonusItem,
	    int year, int month, int quarter, String payType,
	    String monthBonus, String fixedName, String fixedDesc,
	    float adClickCost, float bonusPercent, float bonusMoney,
	    Date createDate, Date updateDate) {
	this.pfpCustomerInfo = pfpCustomerInfo;
	this.pfdCustomerInfo = pfdCustomerInfo;
	this.pfdBonusItem = pfdBonusItem;
	this.year = year;
	this.month = month;
	this.quarter = quarter;
	this.payType = payType;
	this.monthBonus = monthBonus;
	this.fixedName = fixedName;
	this.fixedDesc = fixedDesc;
	this.adClickCost = adClickCost;
	this.bonusPercent = bonusPercent;
	this.bonusMoney = bonusMoney;
	this.createDate = createDate;
	this.updateDate = updateDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "bonus_detail_id", unique = true, nullable = false)
    public Integer getBonusDetailId() {
	return this.bonusDetailId;
    }

    public void setBonusDetailId(Integer bonusDetailId) {
	this.bonusDetailId = bonusDetailId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pfp_customer_info", nullable = false)
    public PfpCustomerInfo getPfpCustomerInfo() {
	return this.pfpCustomerInfo;
    }

    public void setPfpCustomerInfo(PfpCustomerInfo pfpCustomerInfo) {
	this.pfpCustomerInfo = pfpCustomerInfo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pfd_customer_info", nullable = false)
    public PfdCustomerInfo getPfdCustomerInfo() {
	return this.pfdCustomerInfo;
    }

    public void setPfdCustomerInfo(PfdCustomerInfo pfdCustomerInfo) {
	this.pfdCustomerInfo = pfdCustomerInfo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bonus_item_id", nullable = false)
    public PfdBonusItem getPfdBonusItem() {
	return this.pfdBonusItem;
    }

    public void setPfdBonusItem(PfdBonusItem pfdBonusItem) {
	this.pfdBonusItem = pfdBonusItem;
    }

    @Column(name = "year", nullable = false)
    public int getYear() {
	return this.year;
    }

    public void setYear(int year) {
	this.year = year;
    }

    @Column(name = "month", nullable = false)
    public int getMonth() {
	return this.month;
    }

    public void setMonth(int month) {
	this.month = month;
    }

    @Column(name = "quarter", nullable = false)
    public int getQuarter() {
	return this.quarter;
    }

    public void setQuarter(int quarter) {
	this.quarter = quarter;
    }

    @Column(name = "pay_type", nullable = false, length = 1)
    public String getPayType() {
	return this.payType;
    }

    public void setPayType(String payType) {
	this.payType = payType;
    }

    @Column(name = "month_bonus", nullable = false, length = 1)
    public String getMonthBonus() {
	return this.monthBonus;
    }

    public void setMonthBonus(String monthBonus) {
	this.monthBonus = monthBonus;
    }

    @Column(name = "fixed_name", nullable = false, length = 50)
    public String getFixedName() {
	return this.fixedName;
    }

    public void setFixedName(String fixedName) {
	this.fixedName = fixedName;
    }

    @Column(name = "fixed_desc", nullable = false, length = 500)
    public String getFixedDesc() {
	return this.fixedDesc;
    }

    public void setFixedDesc(String fixedDesc) {
	this.fixedDesc = fixedDesc;
    }

    @Column(name = "ad_click_cost", nullable = false, precision = 10)
    public float getAdClickCost() {
	return this.adClickCost;
    }

    public void setAdClickCost(float adClickCost) {
	this.adClickCost = adClickCost;
    }

    @Column(name = "bonus_percent", nullable = false, precision = 10)
    public float getBonusPercent() {
	return this.bonusPercent;
    }

    public void setBonusPercent(float bonusPercent) {
	this.bonusPercent = bonusPercent;
    }

    @Column(name = "bonus_money", nullable = false, precision = 10)
    public float getBonusMoney() {
	return this.bonusMoney;
    }

    public void setBonusMoney(float bonusMoney) {
	this.bonusMoney = bonusMoney;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
	return this.createDate;
    }

    public void setCreateDate(Date createDate) {
	this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", nullable = false, length = 19)
    public Date getUpdateDate() {
	return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
	this.updateDate = updateDate;
    }

}
