package com.pchome.akbpfp.db.pojo;

// Generated 2014/5/5 �U�� 07:01:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PfdUserAdAccountRefId generated by hbm2java
 */
@Embeddable
public class PfdUserAdAccountRefId implements java.io.Serializable {

	private String pfdUserId;
	private String pfpCustomerInfoId;

	public PfdUserAdAccountRefId() {
	}

	public PfdUserAdAccountRefId(String pfdUserId, String pfpCustomerInfoId) {
		this.pfdUserId = pfdUserId;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "pfd_user_id", nullable = false, length = 20)
	public String getPfdUserId() {
		return this.pfdUserId;
	}

	public void setPfdUserId(String pfdUserId) {
		this.pfdUserId = pfdUserId;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PfdUserAdAccountRefId))
			return false;
		PfdUserAdAccountRefId castOther = (PfdUserAdAccountRefId) other;

		return ((this.getPfdUserId() == castOther.getPfdUserId()) || (this
				.getPfdUserId() != null && castOther.getPfdUserId() != null && this
				.getPfdUserId().equals(castOther.getPfdUserId())))
				&& ((this.getPfpCustomerInfoId() == castOther
						.getPfpCustomerInfoId()) || (this
						.getPfpCustomerInfoId() != null
						&& castOther.getPfpCustomerInfoId() != null && this
						.getPfpCustomerInfoId().equals(
								castOther.getPfpCustomerInfoId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPfdUserId() == null ? 0 : this.getPfdUserId().hashCode());
		result = 37
				* result
				+ (getPfpCustomerInfoId() == null ? 0 : this
						.getPfpCustomerInfoId().hashCode());
		return result;
	}

}
