package com.pchome.akbpfp.db.pojo;
// Generated 2018/9/28 �W�� 10:58:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdVideo generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_video")
public class PfpAdVideo implements java.io.Serializable {

	private Integer adVideoSeq;
	private Date adVideoDate;
	private int adVideoTime;
	private String pfdCustomerInfoId;
	private String customerInfoId;
	private String adSeq;
	private int adType;
	private String templateProductSeq;
	private String adPriceType;
	private String adPvclkDevice;
	private int adVideoPlay;
	private int adVideoMusic;
	private int adVideoReplay;
	private int adVideoProcess;
	private int adVideoProcessAmount;
	private int adVideoIdc;
	private Date createDate;
	private Date updateDate;

	public PfpAdVideo() {
	}

	public PfpAdVideo(Date adVideoDate, int adVideoTime, String pfdCustomerInfoId, String customerInfoId, String adSeq,
			int adType, String templateProductSeq, String adPriceType, String adPvclkDevice, int adVideoPlay,
			int adVideoMusic, int adVideoReplay, int adVideoProcess, int adVideoProcessAmount, int adVideoIdc,
			Date createDate, Date updateDate) {
		this.adVideoDate = adVideoDate;
		this.adVideoTime = adVideoTime;
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.customerInfoId = customerInfoId;
		this.adSeq = adSeq;
		this.adType = adType;
		this.templateProductSeq = templateProductSeq;
		this.adPriceType = adPriceType;
		this.adPvclkDevice = adPvclkDevice;
		this.adVideoPlay = adVideoPlay;
		this.adVideoMusic = adVideoMusic;
		this.adVideoReplay = adVideoReplay;
		this.adVideoProcess = adVideoProcess;
		this.adVideoProcessAmount = adVideoProcessAmount;
		this.adVideoIdc = adVideoIdc;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ad_video_seq", unique = true, nullable = false)
	public Integer getAdVideoSeq() {
		return this.adVideoSeq;
	}

	public void setAdVideoSeq(Integer adVideoSeq) {
		this.adVideoSeq = adVideoSeq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ad_video_date", nullable = false, length = 10)
	public Date getAdVideoDate() {
		return this.adVideoDate;
	}

	public void setAdVideoDate(Date adVideoDate) {
		this.adVideoDate = adVideoDate;
	}

	@Column(name = "ad_video_time", nullable = false)
	public int getAdVideoTime() {
		return this.adVideoTime;
	}

	public void setAdVideoTime(int adVideoTime) {
		this.adVideoTime = adVideoTime;
	}

	@Column(name = "pfd_customer_info_id", nullable = false, length = 20)
	public String getPfdCustomerInfoId() {
		return this.pfdCustomerInfoId;
	}

	public void setPfdCustomerInfoId(String pfdCustomerInfoId) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
	}

	@Column(name = "customer_info_id", nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "ad_seq", nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "ad_type", nullable = false)
	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	@Column(name = "template_product_seq", nullable = false, length = 50)
	public String getTemplateProductSeq() {
		return this.templateProductSeq;
	}

	public void setTemplateProductSeq(String templateProductSeq) {
		this.templateProductSeq = templateProductSeq;
	}

	@Column(name = "ad_price_type", nullable = false, length = 3)
	public String getAdPriceType() {
		return this.adPriceType;
	}

	public void setAdPriceType(String adPriceType) {
		this.adPriceType = adPriceType;
	}

	@Column(name = "ad_pvclk_device", nullable = false, length = 20)
	public String getAdPvclkDevice() {
		return this.adPvclkDevice;
	}

	public void setAdPvclkDevice(String adPvclkDevice) {
		this.adPvclkDevice = adPvclkDevice;
	}

	@Column(name = "ad_video_play", nullable = false)
	public int getAdVideoPlay() {
		return this.adVideoPlay;
	}

	public void setAdVideoPlay(int adVideoPlay) {
		this.adVideoPlay = adVideoPlay;
	}

	@Column(name = "ad_video_music", nullable = false)
	public int getAdVideoMusic() {
		return this.adVideoMusic;
	}

	public void setAdVideoMusic(int adVideoMusic) {
		this.adVideoMusic = adVideoMusic;
	}

	@Column(name = "ad_video_replay", nullable = false)
	public int getAdVideoReplay() {
		return this.adVideoReplay;
	}

	public void setAdVideoReplay(int adVideoReplay) {
		this.adVideoReplay = adVideoReplay;
	}

	@Column(name = "ad_video_process", nullable = false)
	public int getAdVideoProcess() {
		return this.adVideoProcess;
	}

	public void setAdVideoProcess(int adVideoProcess) {
		this.adVideoProcess = adVideoProcess;
	}

	@Column(name = "ad_video_process_amount", nullable = false)
	public int getAdVideoProcessAmount() {
		return this.adVideoProcessAmount;
	}

	public void setAdVideoProcessAmount(int adVideoProcessAmount) {
		this.adVideoProcessAmount = adVideoProcessAmount;
	}

	@Column(name = "ad_video_idc", nullable = false)
	public int getAdVideoIdc() {
		return this.adVideoIdc;
	}

	public void setAdVideoIdc(int adVideoIdc) {
		this.adVideoIdc = adVideoIdc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
