package com.pchome.akbpfp.db.pojo;
// Generated 2017/8/21 �U�� 03:11:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PfpAdGift generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_gift", catalog = "akb_video", uniqueConstraints = {
		@UniqueConstraint(columnNames = "customer_info_id"), @UniqueConstraint(columnNames = "ad_gift_sno"),
		@UniqueConstraint(columnNames = "order_id") })
public class PfpAdGift implements java.io.Serializable {

	private Integer adGiftId;
	private String adGiftName;
	private String adGiftSno;
	private int adGiftPrice;
	private String customerInfoId;
	private String orderId;
	private Date openDate;
	private String transDetail;
	private int adGiftStatus;
	private Date adGiftEndDate;
	private int testSno;
	private Date adGiftCreateDate;
	private Date adGiftUpdateDate;

	public PfpAdGift() {
	}

	public PfpAdGift(String adGiftName, String adGiftSno, int adGiftPrice, String transDetail, int adGiftStatus,
			Date adGiftEndDate, int testSno, Date adGiftCreateDate, Date adGiftUpdateDate) {
		this.adGiftName = adGiftName;
		this.adGiftSno = adGiftSno;
		this.adGiftPrice = adGiftPrice;
		this.transDetail = transDetail;
		this.adGiftStatus = adGiftStatus;
		this.adGiftEndDate = adGiftEndDate;
		this.testSno = testSno;
		this.adGiftCreateDate = adGiftCreateDate;
		this.adGiftUpdateDate = adGiftUpdateDate;
	}

	public PfpAdGift(String adGiftName, String adGiftSno, int adGiftPrice, String customerInfoId, String orderId,
			Date openDate, String transDetail, int adGiftStatus, Date adGiftEndDate, int testSno, Date adGiftCreateDate,
			Date adGiftUpdateDate) {
		this.adGiftName = adGiftName;
		this.adGiftSno = adGiftSno;
		this.adGiftPrice = adGiftPrice;
		this.customerInfoId = customerInfoId;
		this.orderId = orderId;
		this.openDate = openDate;
		this.transDetail = transDetail;
		this.adGiftStatus = adGiftStatus;
		this.adGiftEndDate = adGiftEndDate;
		this.testSno = testSno;
		this.adGiftCreateDate = adGiftCreateDate;
		this.adGiftUpdateDate = adGiftUpdateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ad_gift_id", unique = true, nullable = false)
	public Integer getAdGiftId() {
		return this.adGiftId;
	}

	public void setAdGiftId(Integer adGiftId) {
		this.adGiftId = adGiftId;
	}

	@Column(name = "ad_gift_name", nullable = false, length = 20)
	public String getAdGiftName() {
		return this.adGiftName;
	}

	public void setAdGiftName(String adGiftName) {
		this.adGiftName = adGiftName;
	}

	@Column(name = "ad_gift_sno", unique = true, nullable = false, length = 10)
	public String getAdGiftSno() {
		return this.adGiftSno;
	}

	public void setAdGiftSno(String adGiftSno) {
		this.adGiftSno = adGiftSno;
	}

	@Column(name = "ad_gift_price", nullable = false)
	public int getAdGiftPrice() {
		return this.adGiftPrice;
	}

	public void setAdGiftPrice(int adGiftPrice) {
		this.adGiftPrice = adGiftPrice;
	}

	@Column(name = "customer_info_id", unique = true, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "order_id", unique = true, length = 20)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "open_date", length = 0)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Column(name = "trans_detail", nullable = false, length = 2)
	public String getTransDetail() {
		return this.transDetail;
	}

	public void setTransDetail(String transDetail) {
		this.transDetail = transDetail;
	}

	@Column(name = "ad_gift_status", nullable = false)
	public int getAdGiftStatus() {
		return this.adGiftStatus;
	}

	public void setAdGiftStatus(int adGiftStatus) {
		this.adGiftStatus = adGiftStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ad_gift_end_date", nullable = false, length = 0)
	public Date getAdGiftEndDate() {
		return this.adGiftEndDate;
	}

	public void setAdGiftEndDate(Date adGiftEndDate) {
		this.adGiftEndDate = adGiftEndDate;
	}

	@Column(name = "test_sno", nullable = false)
	public int getTestSno() {
		return this.testSno;
	}

	public void setTestSno(int testSno) {
		this.testSno = testSno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ad_gift_create_date", nullable = false, length = 0)
	public Date getAdGiftCreateDate() {
		return this.adGiftCreateDate;
	}

	public void setAdGiftCreateDate(Date adGiftCreateDate) {
		this.adGiftCreateDate = adGiftCreateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ad_gift_update_date", nullable = false, length = 0)
	public Date getAdGiftUpdateDate() {
		return this.adGiftUpdateDate;
	}

	public void setAdGiftUpdateDate(Date adGiftUpdateDate) {
		this.adGiftUpdateDate = adGiftUpdateDate;
	}

}
