package com.pchome.akbpfp.db.pojo;
// Generated 2017/9/22 �W�� 10:31:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdVideoSource generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_video_source")
public class PfpAdVideoSource implements java.io.Serializable {

	private String adVideoSeq;
	private String adVideoName;
	private Integer adVideoSecond;
	private String adVideoPath;
	private int adVideoStatus;
	private String adVideoUrl;
	private Date updateDate;
	private Date createDate;

	public PfpAdVideoSource() {
	}

	public PfpAdVideoSource(String adVideoSeq, String adVideoPath, int adVideoStatus, String adVideoUrl,
			Date updateDate, Date createDate) {
		this.adVideoSeq = adVideoSeq;
		this.adVideoPath = adVideoPath;
		this.adVideoStatus = adVideoStatus;
		this.adVideoUrl = adVideoUrl;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpAdVideoSource(String adVideoSeq, String adVideoName, Integer adVideoSecond, String adVideoPath,
			int adVideoStatus, String adVideoUrl, Date updateDate, Date createDate) {
		this.adVideoSeq = adVideoSeq;
		this.adVideoName = adVideoName;
		this.adVideoSecond = adVideoSecond;
		this.adVideoPath = adVideoPath;
		this.adVideoStatus = adVideoStatus;
		this.adVideoUrl = adVideoUrl;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "ad_video_seq", unique = true, nullable = false, length = 20)
	public String getAdVideoSeq() {
		return this.adVideoSeq;
	}

	public void setAdVideoSeq(String adVideoSeq) {
		this.adVideoSeq = adVideoSeq;
	}

	@Column(name = "ad_video_name", length = 20)
	public String getAdVideoName() {
		return this.adVideoName;
	}

	public void setAdVideoName(String adVideoName) {
		this.adVideoName = adVideoName;
	}

	@Column(name = "ad_video_second")
	public Integer getAdVideoSecond() {
		return this.adVideoSecond;
	}

	public void setAdVideoSecond(Integer adVideoSecond) {
		this.adVideoSecond = adVideoSecond;
	}

	@Column(name = "ad_video_path", nullable = false, length = 2048)
	public String getAdVideoPath() {
		return this.adVideoPath;
	}

	public void setAdVideoPath(String adVideoPath) {
		this.adVideoPath = adVideoPath;
	}

	@Column(name = "ad_video_status", nullable = false)
	public int getAdVideoStatus() {
		return this.adVideoStatus;
	}

	public void setAdVideoStatus(int adVideoStatus) {
		this.adVideoStatus = adVideoStatus;
	}

	@Column(name = "ad_video_url", nullable = false, length = 2048)
	public String getAdVideoUrl() {
		return this.adVideoUrl;
	}

	public void setAdVideoUrl(String adVideoUrl) {
		this.adVideoUrl = adVideoUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
