package com.pchome.akbpfp.db.pojo;
// Generated 2017/8/21 �U�� 03:11:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpBuAccount generated by hbm2java
 */
@Entity
@Table(name = "pfp_bu_account", catalog = "akb_video")
public class PfpBuAccount implements java.io.Serializable {

	private Integer id;
	private String buId;
	private String pcId;
	private String pfdCustomerId;
	private String buName;
	private String buUrl;
	private int pfpStatus;
	private Date updateDate;
	private Date createDate;

	public PfpBuAccount() {
	}

	public PfpBuAccount(String buId, String pcId, String pfdCustomerId, String buName, String buUrl, int pfpStatus,
			Date updateDate, Date createDate) {
		this.buId = buId;
		this.pcId = pcId;
		this.pfdCustomerId = pfdCustomerId;
		this.buName = buName;
		this.buUrl = buUrl;
		this.pfpStatus = pfpStatus;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bu_id", nullable = false, length = 20)
	public String getBuId() {
		return this.buId;
	}

	public void setBuId(String buId) {
		this.buId = buId;
	}

	@Column(name = "pc_id", nullable = false, length = 20)
	public String getPcId() {
		return this.pcId;
	}

	public void setPcId(String pcId) {
		this.pcId = pcId;
	}

	@Column(name = "pfd_customer_id", nullable = false, length = 20)
	public String getPfdCustomerId() {
		return this.pfdCustomerId;
	}

	public void setPfdCustomerId(String pfdCustomerId) {
		this.pfdCustomerId = pfdCustomerId;
	}

	@Column(name = "bu_name", nullable = false, length = 20)
	public String getBuName() {
		return this.buName;
	}

	public void setBuName(String buName) {
		this.buName = buName;
	}

	@Column(name = "bu_url", nullable = false, length = 2048)
	public String getBuUrl() {
		return this.buUrl;
	}

	public void setBuUrl(String buUrl) {
		this.buUrl = buUrl;
	}

	@Column(name = "pfp_status", nullable = false)
	public int getPfpStatus() {
		return this.pfpStatus;
	}

	public void setPfpStatus(int pfpStatus) {
		this.pfpStatus = pfpStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
