package com.pchome.akbpfp.db.pojo;
// Generated 2018/10/4 �W�� 10:06:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogSetup generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_setup")
public class PfpCatalogSetup implements java.io.Serializable {

	private Integer catalogSetupSeq;
	private String pfpCustomerInfoId;
	private String catalogSetupKey;
	private String catalogSetupValue;
	private Date updateDate;
	private Date createDate;

	public PfpCatalogSetup() {
	}

	public PfpCatalogSetup(String pfpCustomerInfoId, String catalogSetupKey, String catalogSetupValue, Date updateDate,
			Date createDate) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.catalogSetupKey = catalogSetupKey;
		this.catalogSetupValue = catalogSetupValue;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "catalog_setup_seq", unique = true, nullable = false)
	public Integer getCatalogSetupSeq() {
		return this.catalogSetupSeq;
	}

	public void setCatalogSetupSeq(Integer catalogSetupSeq) {
		this.catalogSetupSeq = catalogSetupSeq;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "catalog_setup_key", nullable = false, length = 20)
	public String getCatalogSetupKey() {
		return this.catalogSetupKey;
	}

	public void setCatalogSetupKey(String catalogSetupKey) {
		this.catalogSetupKey = catalogSetupKey;
	}

	@Column(name = "catalog_setup_value", nullable = false, length = 20)
	public String getCatalogSetupValue() {
		return this.catalogSetupValue;
	}

	public void setCatalogSetupValue(String catalogSetupValue) {
		this.catalogSetupValue = catalogSetupValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
