package com.pchome.akbpfp.db.pojo;
// Generated 2018/11/2 �W�� 09:57:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogProdEcError generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_prod_ec_error")
public class PfpCatalogProdEcError implements java.io.Serializable {

	private Integer id;
	private PfpCatalogUploadLog pfpCatalogUploadLog;
	private int catalogProdErrItem;
	private String catalogProdSeq;
	private String catalogSeq;
	private String ecName;
	private String ecTitle;
	private String ecImg;
	private String ecUrl;
	private int ecPrice;
	private int ecDiscountPrice;
	private String ecStockStatus;
	private String ecUseStatus;
	private String ecCategory;
	private Date createDate;

	public PfpCatalogProdEcError() {
	}

	public PfpCatalogProdEcError(PfpCatalogUploadLog pfpCatalogUploadLog, int catalogProdErrItem, String catalogProdSeq,
			String catalogSeq, String ecName, String ecTitle, String ecImg, String ecUrl, int ecPrice,
			int ecDiscountPrice, String ecStockStatus, String ecUseStatus, String ecCategory, Date createDate) {
		this.pfpCatalogUploadLog = pfpCatalogUploadLog;
		this.catalogProdErrItem = catalogProdErrItem;
		this.catalogProdSeq = catalogProdSeq;
		this.catalogSeq = catalogSeq;
		this.ecName = ecName;
		this.ecTitle = ecTitle;
		this.ecImg = ecImg;
		this.ecUrl = ecUrl;
		this.ecPrice = ecPrice;
		this.ecDiscountPrice = ecDiscountPrice;
		this.ecStockStatus = ecStockStatus;
		this.ecUseStatus = ecUseStatus;
		this.ecCategory = ecCategory;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalog_upload_log_seq", nullable = false)
	public PfpCatalogUploadLog getPfpCatalogUploadLog() {
		return this.pfpCatalogUploadLog;
	}

	public void setPfpCatalogUploadLog(PfpCatalogUploadLog pfpCatalogUploadLog) {
		this.pfpCatalogUploadLog = pfpCatalogUploadLog;
	}

	@Column(name = "catalog_prod_err_item", nullable = false)
	public int getCatalogProdErrItem() {
		return this.catalogProdErrItem;
	}

	public void setCatalogProdErrItem(int catalogProdErrItem) {
		this.catalogProdErrItem = catalogProdErrItem;
	}

	@Column(name = "catalog_prod_seq", nullable = false, length = 1024)
	public String getCatalogProdSeq() {
		return this.catalogProdSeq;
	}

	public void setCatalogProdSeq(String catalogProdSeq) {
		this.catalogProdSeq = catalogProdSeq;
	}

	@Column(name = "catalog_seq", nullable = false, length = 20)
	public String getCatalogSeq() {
		return this.catalogSeq;
	}

	public void setCatalogSeq(String catalogSeq) {
		this.catalogSeq = catalogSeq;
	}

	@Column(name = "ec_name", nullable = false, length = 1024)
	public String getEcName() {
		return this.ecName;
	}

	public void setEcName(String ecName) {
		this.ecName = ecName;
	}

	@Column(name = "ec_title", nullable = false, length = 1024)
	public String getEcTitle() {
		return this.ecTitle;
	}

	public void setEcTitle(String ecTitle) {
		this.ecTitle = ecTitle;
	}

	@Column(name = "ec_img", nullable = false, length = 2048)
	public String getEcImg() {
		return this.ecImg;
	}

	public void setEcImg(String ecImg) {
		this.ecImg = ecImg;
	}

	@Column(name = "ec_url", nullable = false, length = 2048)
	public String getEcUrl() {
		return this.ecUrl;
	}

	public void setEcUrl(String ecUrl) {
		this.ecUrl = ecUrl;
	}

	@Column(name = "ec_price", nullable = false)
	public int getEcPrice() {
		return this.ecPrice;
	}

	public void setEcPrice(int ecPrice) {
		this.ecPrice = ecPrice;
	}

	@Column(name = "ec_discount_price", nullable = false)
	public int getEcDiscountPrice() {
		return this.ecDiscountPrice;
	}

	public void setEcDiscountPrice(int ecDiscountPrice) {
		this.ecDiscountPrice = ecDiscountPrice;
	}

	@Column(name = "ec_stock_status", nullable = false, length = 1)
	public String getEcStockStatus() {
		return this.ecStockStatus;
	}

	public void setEcStockStatus(String ecStockStatus) {
		this.ecStockStatus = ecStockStatus;
	}

	@Column(name = "ec_use_status", nullable = false, length = 1)
	public String getEcUseStatus() {
		return this.ecUseStatus;
	}

	public void setEcUseStatus(String ecUseStatus) {
		this.ecUseStatus = ecUseStatus;
	}

	@Column(name = "ec_category", nullable = false, length = 50)
	public String getEcCategory() {
		return this.ecCategory;
	}

	public void setEcCategory(String ecCategory) {
		this.ecCategory = ecCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
