package com.pchome.akbpfp.db.pojo;
// Generated 2018/8/7 �U�� 01:54:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogUploadErrLog generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_upload_err_log")
public class PfpCatalogUploadErrLog implements java.io.Serializable {

	private Integer catalogUploadErrLogSeq;
	private PfpCatalogUploadLog pfpCatalogUploadLog;
	private String catalogProdEcSeq;
	private String catalogErrItem;
	private String catalogErrReason;
	private String catalogErrRawdata;
	private Date updateDate;
	private Date createDate;

	public PfpCatalogUploadErrLog() {
	}

	public PfpCatalogUploadErrLog(PfpCatalogUploadLog pfpCatalogUploadLog, String catalogProdEcSeq,
			String catalogErrItem, String catalogErrReason, String catalogErrRawdata, Date updateDate,
			Date createDate) {
		this.pfpCatalogUploadLog = pfpCatalogUploadLog;
		this.catalogProdEcSeq = catalogProdEcSeq;
		this.catalogErrItem = catalogErrItem;
		this.catalogErrReason = catalogErrReason;
		this.catalogErrRawdata = catalogErrRawdata;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "catalog_upload_err_log_seq", unique = true, nullable = false)
	public Integer getCatalogUploadErrLogSeq() {
		return this.catalogUploadErrLogSeq;
	}

	public void setCatalogUploadErrLogSeq(Integer catalogUploadErrLogSeq) {
		this.catalogUploadErrLogSeq = catalogUploadErrLogSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalog_upload_log_seq", nullable = false)
	public PfpCatalogUploadLog getPfpCatalogUploadLog() {
		return this.pfpCatalogUploadLog;
	}

	public void setPfpCatalogUploadLog(PfpCatalogUploadLog pfpCatalogUploadLog) {
		this.pfpCatalogUploadLog = pfpCatalogUploadLog;
	}

	@Column(name = "catalog_prod_ec_seq", nullable = false, length = 1024)
	public String getCatalogProdEcSeq() {
		return this.catalogProdEcSeq;
	}

	public void setCatalogProdEcSeq(String catalogProdEcSeq) {
		this.catalogProdEcSeq = catalogProdEcSeq;
	}

	@Column(name = "catalog_err_item", nullable = false, length = 50)
	public String getCatalogErrItem() {
		return this.catalogErrItem;
	}

	public void setCatalogErrItem(String catalogErrItem) {
		this.catalogErrItem = catalogErrItem;
	}

	@Column(name = "catalog_err_reason", nullable = false, length = 1024)
	public String getCatalogErrReason() {
		return this.catalogErrReason;
	}

	public void setCatalogErrReason(String catalogErrReason) {
		this.catalogErrReason = catalogErrReason;
	}

	@Column(name = "catalog_err_rawdata", nullable = false, length = 2048)
	public String getCatalogErrRawdata() {
		return this.catalogErrRawdata;
	}

	public void setCatalogErrRawdata(String catalogErrRawdata) {
		this.catalogErrRawdata = catalogErrRawdata;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
