package com.pchome.akbpfp.db.pojo;
// Generated 2018/9/27 �W�� 09:32:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogLogo generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_logo")
public class PfpCatalogLogo implements java.io.Serializable {

	private String catalogLogoSeq;
	private String pfpCustomerInfoId;
	private String catalogLogoType;
	private String catalogLogoUrl;
	private Date updateDate;
	private Date createDate;

	public PfpCatalogLogo() {
	}

	public PfpCatalogLogo(String catalogLogoSeq, String pfpCustomerInfoId, String catalogLogoType,
			String catalogLogoUrl, Date updateDate, Date createDate) {
		this.catalogLogoSeq = catalogLogoSeq;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.catalogLogoType = catalogLogoType;
		this.catalogLogoUrl = catalogLogoUrl;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "catalog_logo_seq", unique = true, nullable = false, length = 20)
	public String getCatalogLogoSeq() {
		return this.catalogLogoSeq;
	}

	public void setCatalogLogoSeq(String catalogLogoSeq) {
		this.catalogLogoSeq = catalogLogoSeq;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "catalog_logo_type", nullable = false, length = 1)
	public String getCatalogLogoType() {
		return this.catalogLogoType;
	}

	public void setCatalogLogoType(String catalogLogoType) {
		this.catalogLogoType = catalogLogoType;
	}

	@Column(name = "catalog_logo_url", nullable = false, length = 2048)
	public String getCatalogLogoUrl() {
		return this.catalogLogoUrl;
	}

	public void setCatalogLogoUrl(String catalogLogoUrl) {
		this.catalogLogoUrl = catalogLogoUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
