package com.pchome.akbpfp.db.pojo;
// Generated 2018/8/1 �U�� 02:45:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogProdEc generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_prod_ec")
public class PfpCatalogProdEc implements java.io.Serializable {

	private Integer id;
	private PfpCatalog pfpCatalog;
	private String catalogProdEcSeq;
	private String prodName;
	private String prodTitle;
	private String prodUrl;
	private int prodPrice;
	private int prodDiscountPrice;
	private String prodStockStatus;
	private String prodUseStatus;
	private String prodCategory;
	private String prodStatus;
	private String prodCheckStatus;
	private Date updateDate;
	private Date createDate;

	public PfpCatalogProdEc() {
	}

	public PfpCatalogProdEc(PfpCatalog pfpCatalog, String catalogProdEcSeq, String prodName, String prodTitle,
			String prodUrl, int prodPrice, int prodDiscountPrice, String prodStockStatus, String prodUseStatus,
			String prodCategory, String prodStatus, String prodCheckStatus, Date updateDate, Date createDate) {
		this.pfpCatalog = pfpCatalog;
		this.catalogProdEcSeq = catalogProdEcSeq;
		this.prodName = prodName;
		this.prodTitle = prodTitle;
		this.prodUrl = prodUrl;
		this.prodPrice = prodPrice;
		this.prodDiscountPrice = prodDiscountPrice;
		this.prodStockStatus = prodStockStatus;
		this.prodUseStatus = prodUseStatus;
		this.prodCategory = prodCategory;
		this.prodStatus = prodStatus;
		this.prodCheckStatus = prodCheckStatus;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalog_seq", nullable = false)
	public PfpCatalog getPfpCatalog() {
		return this.pfpCatalog;
	}

	public void setPfpCatalog(PfpCatalog pfpCatalog) {
		this.pfpCatalog = pfpCatalog;
	}

	@Column(name = "catalog_prod_ec_seq", nullable = false, length = 1024)
	public String getCatalogProdEcSeq() {
		return this.catalogProdEcSeq;
	}

	public void setCatalogProdEcSeq(String catalogProdEcSeq) {
		this.catalogProdEcSeq = catalogProdEcSeq;
	}

	@Column(name = "prod_name", nullable = false, length = 1024)
	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	@Column(name = "prod_title", nullable = false, length = 1024)
	public String getProdTitle() {
		return this.prodTitle;
	}

	public void setProdTitle(String prodTitle) {
		this.prodTitle = prodTitle;
	}

	@Column(name = "prod_url", nullable = false, length = 2048)
	public String getProdUrl() {
		return this.prodUrl;
	}

	public void setProdUrl(String prodUrl) {
		this.prodUrl = prodUrl;
	}

	@Column(name = "prod_price", nullable = false)
	public int getProdPrice() {
		return this.prodPrice;
	}

	public void setProdPrice(int prodPrice) {
		this.prodPrice = prodPrice;
	}

	@Column(name = "prod_discount_price", nullable = false)
	public int getProdDiscountPrice() {
		return this.prodDiscountPrice;
	}

	public void setProdDiscountPrice(int prodDiscountPrice) {
		this.prodDiscountPrice = prodDiscountPrice;
	}

	@Column(name = "prod_stock_status", nullable = false, length = 1)
	public String getProdStockStatus() {
		return this.prodStockStatus;
	}

	public void setProdStockStatus(String prodStockStatus) {
		this.prodStockStatus = prodStockStatus;
	}

	@Column(name = "prod_use_status", nullable = false, length = 1)
	public String getProdUseStatus() {
		return this.prodUseStatus;
	}

	public void setProdUseStatus(String prodUseStatus) {
		this.prodUseStatus = prodUseStatus;
	}

	@Column(name = "prod_category", nullable = false, length = 50)
	public String getProdCategory() {
		return this.prodCategory;
	}

	public void setProdCategory(String prodCategory) {
		this.prodCategory = prodCategory;
	}

	@Column(name = "prod_status", nullable = false, length = 1)
	public String getProdStatus() {
		return this.prodStatus;
	}

	public void setProdStatus(String prodStatus) {
		this.prodStatus = prodStatus;
	}

	@Column(name = "prod_check_status", nullable = false, length = 1)
	public String getProdCheckStatus() {
		return this.prodCheckStatus;
	}

	public void setProdCheckStatus(String prodCheckStatus) {
		this.prodCheckStatus = prodCheckStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
