package com.pchome.akbpfp.db.pojo;
// Generated 2018/11/16 �W�� 10:31:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCode generated by hbm2java
 */
@Entity
@Table(name = "pfp_code")
public class PfpCode implements java.io.Serializable {

	private String paId;
	private String pfpCustomerInfoId;
	private Date updateDate;
	private Date createDate;
	private Set<PfpCodeTracking> pfpCodeTrackings = new HashSet<PfpCodeTracking>(0);
	private Set<PfpCodeConvert> pfpCodeConverts = new HashSet<PfpCodeConvert>(0);

	public PfpCode() {
	}

	public PfpCode(String paId, String pfpCustomerInfoId, Date updateDate, Date createDate) {
		this.paId = paId;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpCode(String paId, String pfpCustomerInfoId, Date updateDate, Date createDate,
			Set<PfpCodeTracking> pfpCodeTrackings, Set<PfpCodeConvert> pfpCodeConverts) {
		this.paId = paId;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.pfpCodeTrackings = pfpCodeTrackings;
		this.pfpCodeConverts = pfpCodeConverts;
	}

	@Id

	@Column(name = "pa_id", unique = true, nullable = false, length = 20)
	public String getPaId() {
		return this.paId;
	}

	public void setPaId(String paId) {
		this.paId = paId;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfpCode")
	public Set<PfpCodeTracking> getPfpCodeTrackings() {
		return this.pfpCodeTrackings;
	}

	public void setPfpCodeTrackings(Set<PfpCodeTracking> pfpCodeTrackings) {
		this.pfpCodeTrackings = pfpCodeTrackings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfpCode")
	public Set<PfpCodeConvert> getPfpCodeConverts() {
		return this.pfpCodeConverts;
	}

	public void setPfpCodeConverts(Set<PfpCodeConvert> pfpCodeConverts) {
		this.pfpCodeConverts = pfpCodeConverts;
	}

}
