package com.pchome.akbpfp.db.pojo;
// Generated 2018/10/4 �U�� 04:15:54 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCatalogGroup generated by hbm2java
 */
@Entity
@Table(name = "pfp_catalog_group")
public class PfpCatalogGroup implements java.io.Serializable {

	private String catalogGroupSeq;
	private PfpCatalog pfpCatalog;
	private String catalogGroupName;
	private Date updateDate;
	private Date createDate;

	public PfpCatalogGroup() {
	}

	public PfpCatalogGroup(String catalogGroupSeq, PfpCatalog pfpCatalog, String catalogGroupName, Date updateDate,
			Date createDate) {
		this.catalogGroupSeq = catalogGroupSeq;
		this.pfpCatalog = pfpCatalog;
		this.catalogGroupName = catalogGroupName;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "catalog_group_seq", unique = true, nullable = false, length = 20)
	public String getCatalogGroupSeq() {
		return this.catalogGroupSeq;
	}

	public void setCatalogGroupSeq(String catalogGroupSeq) {
		this.catalogGroupSeq = catalogGroupSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalog_seq", nullable = false)
	public PfpCatalog getPfpCatalog() {
		return this.pfpCatalog;
	}

	public void setPfpCatalog(PfpCatalog pfpCatalog) {
		this.pfpCatalog = pfpCatalog;
	}

	@Column(name = "catalog_group_name", nullable = false, length = 20)
	public String getCatalogGroupName() {
		return this.catalogGroupName;
	}

	public void setCatalogGroupName(String catalogGroupName) {
		this.catalogGroupName = catalogGroupName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
