package com.pchome.akbpfp.db.pojo;

// Generated 2017/6/22 �W�� 10:22:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpRefundOrder generated by hbm2java
 */
@Entity
@Table(name = "pfp_refund_order", catalog = "akb")
public class PfpRefundOrder implements java.io.Serializable {

	private String refundOrderId;
	private PfpCustomerInfo pfpCustomerInfo;
	private String orderId;
	private String payType;
	private String refundStatus;
	private float refundPrice;
	private String refundNote;
	private Date refundDate;
	private Date updateDate;
	private Date createDate;

	public PfpRefundOrder() {
	}

	public PfpRefundOrder(String refundOrderId,
			PfpCustomerInfo pfpCustomerInfo, String payType,
			String refundStatus, float refundPrice, Date refundDate,
			Date updateDate, Date createDate) {
		this.refundOrderId = refundOrderId;
		this.pfpCustomerInfo = pfpCustomerInfo;
		this.payType = payType;
		this.refundStatus = refundStatus;
		this.refundPrice = refundPrice;
		this.refundDate = refundDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfpRefundOrder(String refundOrderId,
			PfpCustomerInfo pfpCustomerInfo, String orderId, String payType,
			String refundStatus, float refundPrice, String refundNote,
			Date refundDate, Date updateDate, Date createDate) {
		this.refundOrderId = refundOrderId;
		this.pfpCustomerInfo = pfpCustomerInfo;
		this.orderId = orderId;
		this.payType = payType;
		this.refundStatus = refundStatus;
		this.refundPrice = refundPrice;
		this.refundNote = refundNote;
		this.refundDate = refundDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "refund_order_id", unique = true, nullable = false, length = 20)
	public String getRefundOrderId() {
		return this.refundOrderId;
	}

	public void setRefundOrderId(String refundOrderId) {
		this.refundOrderId = refundOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfpCustomerInfo getPfpCustomerInfo() {
		return this.pfpCustomerInfo;
	}

	public void setPfpCustomerInfo(PfpCustomerInfo pfpCustomerInfo) {
		this.pfpCustomerInfo = pfpCustomerInfo;
	}

	@Column(name = "order_id", length = 20)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "refund_status", nullable = false, length = 1)
	public String getRefundStatus() {
		return this.refundStatus;
	}

	public void setRefundStatus(String refundStatus) {
		this.refundStatus = refundStatus;
	}

	@Column(name = "refund_price", nullable = false, precision = 10)
	public float getRefundPrice() {
		return this.refundPrice;
	}

	public void setRefundPrice(float refundPrice) {
		this.refundPrice = refundPrice;
	}

	@Column(name = "refund_note", length = 100)
	public String getRefundNote() {
		return this.refundNote;
	}

	public void setRefundNote(String refundNote) {
		this.refundNote = refundNote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "refund_date", nullable = false, length = 10)
	public Date getRefundDate() {
		return this.refundDate;
	}

	public void setRefundDate(Date refundDate) {
		this.refundDate = refundDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
